name: Cross-platform build

on:
  push:
    branches:
      - 'develop'
      - 'master'
  pull_request:
    branches:
      - 'develop'
      - 'master'

jobs:
  cross_build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Build project
        run: |
          if [ "${{ runner.os }}" == "Windows" ]; then
            ./ci.bat
          else
            bash ./ci.sh
          fi
